module AoC2024.Day8.Tests

open System.IO
open NUnit.Framework

let tinyInput1 = """..........
...#......
..........
....a.....
..........
.....a....
..........
......#...
..........
.........."""

[<Test>]
let antinodes1 () =     
    Assert.AreEqual(2, day8 (tinyInput1.Split("\r\n") |> Array.toList))
    ()

let tinyInput2 = """..........
...#......
#.........
....a.....
........a.
.....a....
..#.......
......#...
..........
.........."""

[<Test>]
let antinodes2 () =     
    Assert.AreEqual(4, day8 (tinyInput2.Split("\r\n") |> Array.toList))
    ()

let exampleInput = """......#....#
...#....0...
....#0....#.
..#....0....
....0....#..
.#....A.....
...#........
#......#....
........A...
.........A..
..........#.
..........#."""

[<Test>]
let day8Example () =
    Assert.AreEqual(14, day8 (exampleInput.Split("\r\n") |> Array.toList))
    ()

let tinyExampleB = """T....#....
...T......
.T....#...
.........#
..#.......
..........
...#......
..........
....#.....
.........."""

[<Test>]
let tinyB () =
    Assert.AreEqual(9, day8B (tinyExampleB.Split("\r\n") |> Array.toList))
    ()

[<Test>]
let day8BExample () =
    Assert.AreEqual(34, day8B (exampleInput.Split("\r\n") |> Array.toList))
    ()
    
let input = File.ReadAllLines "./Day8.txt" |> Array.toList

[<Test>]
let day8A () =
    Assert.AreEqual(376, day8 input)
    ()
    
[<Test>]
let day8B () =
    Assert.AreEqual(1352, day8B input)
    ()        